#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
harness_root="$(cd "$script_dir/.." && pwd)"
template_dir="$harness_root/template"
shared_gitignore_dir="$harness_root/sources/gitignore"

target=""
project_name=""
stack=""
provider="neutral"
issue_prefix=""
force=0
dry_run=0

usage() {
  cat <<'EOF'
Usage: bash scripts/init_harness_project.sh \
  --target /abs/path/to/repo \
  --project-name NAME \
  --stack go|python|java|c|go-node|python-node|java-node|c-node|java-c|java-c-node \
  [--provider neutral|github|gitlab] \
  [--issue-prefix PREFIX] \
  [--force] \
  [--dry-run]
EOF
}

escape_replacement() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\//\\/}"
  value="${value//&/\\&}"
  printf '%s' "$value"
}

log() {
  printf '%s\n' "$*"
}

require_arg() {
  local flag="$1"
  local value="${2:-}"
  if [[ -z "$value" ]]; then
    echo "missing value for $flag" >&2
    exit 2
  fi
}

validate_stack() {
  case "$stack" in
    go|python|java|c|go-node|python-node|java-node|c-node|java-c|java-c-node) ;;
    *)
      echo "unsupported stack: $stack" >&2
      exit 2
      ;;
  esac
}

validate_provider() {
  case "$provider" in
    neutral|github|gitlab) ;;
    *)
      echo "unsupported provider: $provider" >&2
      exit 2
      ;;
  esac
}

validate_target() {
  if [[ "$target" != /* ]]; then
    echo "--target must be an absolute path: $target" >&2
    exit 2
  fi

  if [[ -e "$target" && ! -d "$target" ]]; then
    echo "target exists and is not a directory: $target" >&2
    exit 2
  fi
}

obsolete_managed_files=(
  "docs/harness/README.md"
  "docs/harness/prompt-templates.md"
  ".agent/mappings/reference-mapping.yaml"
  ".agent/mappings/knowledge-writeback-mapping.example.yaml"
  "scripts/harness/merge_gate.sh"
  "scripts/harness/escalation_gate.sh"
)

cleanup_obsolete_managed_files() {
  local found=0

  for rel in "${obsolete_managed_files[@]}"; do
    if [[ -e "$target/$rel" ]]; then
      found=1

      if [[ "$force" -eq 1 ]]; then
        if [[ "$dry_run" -eq 1 ]]; then
          log "[dry-run] remove obsolete managed file $target/$rel"
        else
          rm -f "$target/$rel"
        fi
      fi
    fi
  done

  if [[ "$found" -eq 1 && "$force" -ne 1 && "$dry_run" -ne 1 ]]; then
    echo "obsolete managed files detected in target; rerun with --force to clean them before post-check" >&2
    exit 1
  fi
}

copy_file() {
  local src="$1"
  local dest="$2"

  if [[ -e "$dest" && "$force" -ne 1 ]]; then
    echo "refusing to overwrite existing file without --force: $dest" >&2
    exit 1
  fi

  if [[ "$dry_run" -eq 1 ]]; then
    log "[dry-run] copy $src -> $dest"
    return 0
  fi

  mkdir -p "$(dirname "$dest")"
  cp "$src" "$dest"
}

build_gitignore() {
  local output="$1"
  local parts=("$shared_gitignore_dir/base.gitignore")

  case "$stack" in
    go) parts+=("$shared_gitignore_dir/go.gitignore") ;;
    python) parts+=("$shared_gitignore_dir/python.gitignore") ;;
    java) parts+=("$shared_gitignore_dir/java.gitignore") ;;
    c) parts+=("$shared_gitignore_dir/c.gitignore") ;;
    go-node)
      parts+=("$shared_gitignore_dir/go.gitignore")
      parts+=("$shared_gitignore_dir/node-frontend.gitignore")
      ;;
    python-node)
      parts+=("$shared_gitignore_dir/python.gitignore")
      parts+=("$shared_gitignore_dir/node-frontend.gitignore")
      ;;
    java-node)
      parts+=("$shared_gitignore_dir/java.gitignore")
      parts+=("$shared_gitignore_dir/node-frontend.gitignore")
      ;;
    c-node)
      parts+=("$shared_gitignore_dir/c.gitignore")
      parts+=("$shared_gitignore_dir/node-frontend.gitignore")
      ;;
    java-c)
      parts+=("$shared_gitignore_dir/java.gitignore")
      parts+=("$shared_gitignore_dir/c.gitignore")
      ;;
    java-c-node)
      parts+=("$shared_gitignore_dir/java.gitignore")
      parts+=("$shared_gitignore_dir/c.gitignore")
      parts+=("$shared_gitignore_dir/node-frontend.gitignore")
      ;;
  esac

  if [[ "$dry_run" -eq 1 ]]; then
    log "[dry-run] build .gitignore from:"
    printf '  - %s\n' "${parts[@]}"
    return 0
  fi

  {
    printf '# Generated by init_harness_project.sh\n\n'
    for part in "${parts[@]}"; do
      cat "$part"
      printf '\n'
    done
  } >"$output"
}

replace_placeholders() {
  local file="$1"
  local project_escaped
  local prefix_escaped
  local provider_escaped

  project_escaped="$(escape_replacement "$project_name")"
  prefix_escaped="$(escape_replacement "$issue_prefix")"
  provider_escaped="$(escape_replacement "$provider")"

  perl -0pi -e "s/__PROJECT_NAME__/$project_escaped/g; s/__ISSUE_PREFIX__/$prefix_escaped/g; s/__PROVIDER__/$provider_escaped/g" "$file"
}

postprocess_text_files() {
  local files=(
    "$target/AGENTS.md"
    "$target/README.md"
    "$target/.agent/PLANS.md"
    "$target/docs/harness/control-plane.md"
    "$target/docs/harness/linear.md"
  )

  if [[ "$dry_run" -eq 1 ]]; then
    log "[dry-run] replace placeholders in template text files"
    return 0
  fi

  for file in "${files[@]}"; do
    replace_placeholders "$file"
  done
}

make_scripts_executable() {
  if [[ "$dry_run" -eq 1 ]]; then
    log "[dry-run] chmod +x scripts/harness/*.sh"
    return 0
  fi

  chmod +x "$target/scripts/harness/"*.sh
}

run_post_check() {
  if [[ "$dry_run" -eq 1 ]]; then
    log "[dry-run] run bash scripts/harness/check.sh"
    return 0
  fi

  (cd "$target" && bash scripts/harness/check.sh)
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)
      require_arg "$1" "${2:-}"
      target="$2"
      shift 2
      ;;
    --project-name)
      require_arg "$1" "${2:-}"
      project_name="$2"
      shift 2
      ;;
    --stack)
      require_arg "$1" "${2:-}"
      stack="$2"
      shift 2
      ;;
    --provider)
      require_arg "$1" "${2:-}"
      provider="$2"
      shift 2
      ;;
    --issue-prefix)
      require_arg "$1" "${2:-}"
      issue_prefix="$2"
      shift 2
      ;;
    --force)
      force=1
      shift
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$target" || -z "$project_name" || -z "$stack" ]]; then
  usage >&2
  exit 2
fi

validate_stack
validate_provider
validate_target

if [[ "$dry_run" -eq 0 ]]; then
  mkdir -p "$target"
fi

managed_files=(
  "AGENTS.md"
  "README.md"
  "Makefile"
  ".agent/PLANS.md"
  ".agent/plans/TEMPLATE.md"
  ".agent/plans/EXAMPLE-implementation.md"
  ".agent/state/TEMPLATE.md"
  ".agent/runs/TEMPLATE.md"
  "docs/harness/control-plane.md"
  "docs/harness/linear.md"
  "docs/harness/project-constraints.md"
  "docs/test/RUNBOOK_TEMPLATE.md"
  "scripts/harness/check.sh"
  "scripts/harness/common.sh"
  "scripts/harness/review_gate.sh"
)

for rel in "${managed_files[@]}"; do
  copy_file "$template_dir/$rel" "$target/$rel"
done

cleanup_obsolete_managed_files

if [[ -e "$target/.gitignore" && "$force" -ne 1 && "$dry_run" -ne 1 ]]; then
  echo "refusing to overwrite existing file without --force: $target/.gitignore" >&2
  exit 1
fi

if [[ "$dry_run" -eq 1 ]]; then
  log "[dry-run] copy $template_dir/.gitignore -> $target/.gitignore (will be rebuilt)"
else
  mkdir -p "$(dirname "$target/.gitignore")"
  cp "$template_dir/.gitignore" "$target/.gitignore"
fi

build_gitignore "$target/.gitignore"
postprocess_text_files
make_scripts_executable
run_post_check

log "initialized harness into: $target"
log "stack: $stack"
log "provider: $provider"
log "next steps:"
log "  1. inspect .gitignore and add repo-specific local files"
log "  2. read docs/harness/ and docs/test/RUNBOOK_TEMPLATE.md"
log "  3. fill docs/harness/project-constraints.md with repo-specific mechanical constraints"
log "  4. update README and AGENTS with real project context"
log "  5. create the first plan in .agent/plans/"
log "  6. if an agent is driving init, follow $harness_root/agent-init-project.md to add .agent/prompts/ + .agent/guides/"
